import "./globals.css";
import type { Metadata } from "next";
import { twMerge } from "tailwind-merge";
import NavBar from "./navbar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          inter.className,
          "relative bg-black text-white dark:bg-black dark:text-white"
        )}
      >
        <header className="bg-black text-white shadow-md">
          <NavBar />
        </header>
        <main className="lg:p-20 mx-auto max-w-7xl">{children}</main>
      </body>
    </html>
  );
}
